#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

makehook() {
  IMAGE=$1
  HOOK=$2

  id=$(docker run -d $IMAGE /bin/bash -c "test -f app/Makefile && grep -q "^$HOOK:" app/Makefile")

  # Check for Makefile and $HOOK
  if [ $(docker wait $id) -ne 0 ]; then
    exit 0
  fi

  echo "       make-hook: triggering '$HOOK'"
  id=$(docker run -d $IMAGE /exec make $HOOK)
  docker attach $id
  test "$(docker wait $id)" -eq 0
  docker commit $id $IMAGE > /dev/null
  echo "       make-hook: triggered '$HOOK'"
}
